CREATE TABLE usuarios (
    id INT PRIMARY KEY AUTO_INCREMENT,
    nome TEXT,
    senha TEXT
);

CREATE TABLE produtos (
    id INT PRIMARY KEY AUTO_INCREMENT,
    imagem TEXT,
    valor INT,
    descricao TEXT
);

INSERT INTO usuarios (nome, senha) VALUES ('João Silva', 'senha123');
INSERT INTO usuarios (nome, senha) VALUES ('Maria Oliveira', 'senha456');
INSERT INTO usuarios (nome, senha) VALUES ('Thomas Turbano', 'senha789');
INSERT INTO usuarios (nome, senha) VALUES ('Deide Costa', 'senha101');
INSERT INTO usuarios (nome, senha) VALUES ('Cuca Beludo', 'senha202');
INSERT INTO usuarios (nome, senha) VALUES ('Ana Souza', 'senha303');
INSERT INTO usuarios (nome, senha) VALUES ('Carlos Alberto', 'senha404');
INSERT INTO usuarios (nome, senha) VALUES ('Fernanda Martins', 'senha505');
INSERT INTO usuarios (nome, senha) VALUES ('Ricardo Pereira', 'senha606');
INSERT INTO usuarios (nome, senha) VALUES ('Patricia Lima', 'senha707');
INSERT INTO usuarios (nome, senha) VALUES ('Raul Mendes', 'senha808');
INSERT INTO usuarios (nome, senha) VALUES ('Juliana Rocha', 'senha909');
INSERT INTO usuarios (nome, senha) VALUES ('Eduardo Santos', 'senha010');
INSERT INTO usuarios (nome, senha) VALUES ('Tatiane Costa', 'senha111');
INSERT INTO usuarios (nome, senha) VALUES ('Felipe Ferreira', 'senha212');
INSERT INTO usuarios (nome, senha) VALUES ('Larissa Oliveira', 'senha313');
INSERT INTO usuarios (nome, senha) VALUES ('Jorge Silva', 'senha414');
INSERT INTO usuarios (nome, senha) VALUES ('Patricia Souza', 'senha515');
INSERT INTO usuarios (nome, senha) VALUES ('Roberto Alves', 'senha616');
INSERT INTO usuarios (nome, senha) VALUES ('Gabriela Lima', 'senha717');
INSERT INTO usuarios (nome, senha) VALUES ('Mauro Oliveira', 'senha818');
INSERT INTO usuarios (nome, senha) VALUES ('Claudia Rocha', 'senha919');
INSERT INTO usuarios (nome, senha) VALUES ('Fábio Lima', 'senha020');
INSERT INTO usuarios (nome, senha) VALUES ('Vera Martins', 'senha121');
INSERT INTO usuarios (nome, senha) VALUES ('Fernando Costa', 'senha222');
INSERT INTO usuarios (nome, senha) VALUES ('Cláudia Pereira', 'senha323');
INSERT INTO usuarios (nome, senha) VALUES ('Marcelo Ferreira', 'senha424');
INSERT INTO usuarios (nome, senha) VALUES ('Rita Oliveira', 'senha525');
INSERT INTO usuarios (nome, senha) VALUES ('Adriana Silva', 'senha626');
INSERT INTO usuarios (nome, senha) VALUES ('Danilo Costa', 'senha727');
INSERT INTO usuarios (nome, senha) VALUES ('Bruna Mendes', 'senha828');
INSERT INTO usuarios (nome, senha) VALUES ('Gustavo Rocha', 'senha929');
INSERT INTO usuarios (nome, senha) VALUES ('Sílvia Oliveira', 'senha030');
INSERT INTO usuarios (nome, senha) VALUES ('Eduarda Lima', 'senha131');
INSERT INTO usuarios (nome, senha) VALUES ('André Pereira', 'senha232');
INSERT INTO usuarios (nome, senha) VALUES ('Thiago Costa', 'senha333');
INSERT INTO usuarios (nome, senha) VALUES ('Mariana Santos', 'senha434');
INSERT INTO usuarios (nome, senha) VALUES ('Flávia Rocha', 'senha535');
INSERT INTO usuarios (nome, senha) VALUES ('Lúcia Alves', 'senha636');
INSERT INTO usuarios (nome, senha) VALUES ('Marco Lima', 'senha737');
INSERT INTO usuarios (nome, senha) VALUES ('Tatiane Ferreira', 'senha838');
INSERT INTO usuarios (nome, senha) VALUES ('José Silva', 'senha939');
INSERT INTO usuarios (nome, senha) VALUES ('Carla Costa', 'senha040');
INSERT INTO usuarios (nome, senha) VALUES ('Marcio Pereira', 'senha141');
INSERT INTO usuarios (nome, senha) VALUES ('Natalia Lima', 'senha242');
INSERT INTO usuarios (nome, senha) VALUES ('Gustavo Souza', 'senha343');
INSERT INTO usuarios (nome, senha) VALUES ('Beatriz Rocha', 'senha444');
INSERT INTO usuarios (nome, senha) VALUES ('Isabela Alves', 'senha545');
INSERT INTO usuarios (nome, senha) VALUES ('Raquel Pereira', 'senha646');
INSERT INTO usuarios (nome, senha) VALUES ('Vítor Costa', 'senha747');
INSERT INTO usuarios (nome, senha) VALUES ('Roberta Santos', 'senha848');
INSERT INTO usuarios (nome, senha) VALUES ('Sandra Lima', 'senha949');
INSERT INTO usuarios (nome, senha) VALUES ('Otávio Rocha', 'senha050');
INSERT INTO usuarios (nome, senha) VALUES ('Rogério Ferreira', 'senha151');
INSERT INTO usuarios (nome, senha) VALUES ('Renata Silva', 'senha252');
INSERT INTO usuarios (nome, senha) VALUES ('Patrícia Alves', 'senha353');
INSERT INTO usuarios (nome, senha) VALUES ('Gisele Lima', 'senha454');
INSERT INTO usuarios (nome, senha) VALUES ('Carlos Rocha', 'senha555');
INSERT INTO usuarios (nome, senha) VALUES ('Kátia Santos', 'senha656');
INSERT INTO usuarios (nome, senha) VALUES ('Tiago Pereira', 'senha757');
INSERT INTO usuarios (nome, senha) VALUES ('Clarice Costa', 'senha858');
INSERT INTO usuarios (nome, senha) VALUES ('Marcela Lima', 'senha959');
INSERT INTO usuarios (nome, senha) VALUES ('Caroline Rocha', 'senha060');
INSERT INTO usuarios (nome, senha) VALUES ('Aline Pereira', 'senha161');
INSERT INTO usuarios (nome, senha) VALUES ('Felipe Souza', 'senha262');
INSERT INTO usuarios (nome, senha) VALUES ('Rafael Lima', 'senha363');
INSERT INTO usuarios (nome, senha) VALUES ('Leandro Costa', 'senha464');
INSERT INTO usuarios (nome, senha) VALUES ('Gilberto Rocha', 'senha565');
INSERT INTO usuarios (nome, senha) VALUES ('Karine Lima', 'senha666');
INSERT INTO usuarios (nome, senha) VALUES ('Tiago Alves', 'senha767');
INSERT INTO usuarios (nome, senha) VALUES ('Juliana Ferreira', 'senha868');
INSERT INTO usuarios (nome, senha) VALUES ('Fátima Costa', 'senha969');
INSERT INTO usuarios (nome, senha) VALUES ('Célia Santos', 'senha070');
INSERT INTO usuarios (nome, senha) VALUES ('Vera Rocha', 'senha171');
INSERT INTO usuarios (nome, senha) VALUES ('Luiz Lima', 'senha272');
INSERT INTO usuarios (nome, senha) VALUES ('Jorge Silva', 'senha414');
INSERT INTO usuarios (nome, senha) VALUES ('Patricia Souza', 'senha515');
INSERT INTO usuarios (nome, senha) VALUES ('Roberto Alves', 'senha616');
INSERT INTO usuarios (nome, senha) VALUES ('Gabriela Lima', 'senha717');
INSERT INTO usuarios (nome, senha) VALUES ('Mauro Oliveira', 'senha818');

INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem1.jpg', 10, 'Naftalina');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem2.jpg', 25, 'Balinha de Gengibre');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem3.jpg', 15, 'Dipirona');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem4.jpg', 12, 'Tadalafila');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem5.jpg', 18, 'Paracetamol');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem6.jpg', 22, 'Aspirina');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem7.jpg', 8, 'Gripe A');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem8.jpg', 20, 'Xarope para Tosse');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem9.jpg', 30, 'Antialérgico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem10.jpg', 35, 'Anti-inflamatório');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem11.jpg', 12, 'Balm para Dor Muscular');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem12.jpg', 18, 'Corticoide');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem13.jpg', 20, 'Amoxicilina');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem14.jpg', 25, 'Cloridrato de Fluoxetina');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem15.jpg', 28, 'Antibiótico Cefalexina');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem16.jpg', 15, 'Pomada para queimaduras');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem17.jpg', 8, 'Vitaminas C');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem18.jpg', 22, 'Suplemento de Cálcio');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem19.jpg', 27, 'Analgésico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem20.jpg', 18, 'Calmante Natural');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem21.jpg', 14, 'Remédio para Estômago');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem22.jpg', 25, 'Anticoncepcional');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem23.jpg', 17, 'Antiácido');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem24.jpg', 12, 'Creme Hidratante');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem25.jpg', 30, 'Gelo Terapêutico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem26.jpg', 35, 'Descongestionante Nasal');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem27.jpg', 20, 'Pomada Antisséptica');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem28.jpg', 10, 'Anti-inflamatório Tópico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem29.jpg', 8, 'Aspirina Infantil');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem30.jpg', 16, 'Spray Nasal');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem31.jpg', 22, 'Soro Fisiológico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem32.jpg', 30, 'Seda Dentária');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem33.jpg', 18, 'Escova de Dente');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem34.jpg', 25, 'Protetor Solar');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem35.jpg', 15, 'Antisséptico Bucal');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem36.jpg', 12, 'Pomada para Candidíase');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem37.jpg', 28, 'Remédio para Cólicas');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem38.jpg', 32, 'Soro Oral');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem39.jpg', 8, 'Termômetro');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem40.jpg', 10, 'Atadura');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem41.jpg', 22, 'Lentes de Contato');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem42.jpg', 17, 'Líquido de Limpeza para Lentes');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem43.jpg', 14, 'Géis para Dor Articular');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem44.jpg', 25, 'Antifúngico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem45.jpg', 35, 'Revestimento de Proteção para Feridas');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem46.jpg', 28, 'Medicação para Hipertensão');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem47.jpg', 18, 'Ferro Suplementar');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem48.jpg', 8, 'Repelente');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem49.jpg', 20, 'Fraldas Descartáveis');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem50.jpg', 15, 'Absorventes');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem51.jpg', 30, 'Pomada para Dermatite');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem52.jpg', 12, 'Escova para Cabelo');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem53.jpg', 10, 'Shampoo Anti-caspa');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem54.jpg', 18, 'Shampoo Infantil');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem55.jpg', 25, 'Hidratante Labial');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem56.jpg', 22, 'Pomada para Picada de Inseto');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem57.jpg', 14, 'Protetor Solar Infantil');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem58.jpg', 35, 'Antigripal');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem59.jpg', 20, 'Desodorante Aerosol');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem60.jpg', 12, 'Desodorante Roll-on');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem61.jpg', 18, 'Medicação para Insônia');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem62.jpg', 25, 'Creme para Celulite');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem63.jpg', 8, 'Papel Higiénico');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem64.jpg', 30, 'Repelente para Ratos');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem65.jpg', 10, 'Medicamento para Acidez Estomacal');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem66.jpg', 27, 'Esparadrapo');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem67.jpg', 14, 'Pomada para Acne');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem68.jpg', 19, 'Desinfetante para as Mãos');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem69.jpg', 22, 'Loção para Dermatite');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem70.jpg', 10, 'Gotas para Cólicas');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem71.jpg', 30, 'Filtro Solar em Spray');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem72.jpg', 12, 'Escova Dental Elétrica');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem73.jpg', 25, 'Medicamento para Dor de Garganta');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem74.jpg', 18, 'Pomada para Psoríase');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem75.jpg', 27, 'Remédio para Triglicerídeos');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem76.jpg', 16, 'Cloroquina');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem77.jpg', 13, 'Xarope para Crianças');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem78.jpg', 12, 'Medicação para Diabetes');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem79.jpg', 18, 'Antibiótico Ointment');
INSERT INTO produtos (imagem, valor, descricao) VALUES ('imagem80.jpg', 25, 'Cicatrização de Feridas');
